# Generated by Django 3.2.3 on 2021-08-06 12:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0008_auto_20210725_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='video',
            field=models.CharField(blank=True, help_text='<b style="color:green;font-size: 12px">*IMPORTANT* Only add either Video link or Image, If you add both, only the image will be shown</b>', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='research_center',
            name='image1',
            field=cloudinary.models.CloudinaryField(help_text='<b style="color:green;font-size: 12px">*IMPORTANT* All three image should be of equal ratio (preffered: 3 x 2 )</b>', max_length=255, verbose_name='image1'),
        ),
    ]
