# Generated by Django 3.2.3 on 2021-08-06 13:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0009_auto_20210806_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_center',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='<b style="color:green;font-size: 15px">*IMPORTANT* All three image should be of equal ratio (preffered: 3 x 2 )</b>', max_length=255, null=True, verbose_name='image1'),
        ),
    ]
