# Generated by Django 3.2.3 on 2021-08-06 13:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0010_alter_research_center_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_center',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
