# Generated by Django 3.2.3 on 2021-08-06 13:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0011_research_center_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_center',
            name='join_us',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='research_center',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='research_center',
            name='video',
            field=models.CharField(blank=True, help_text='<b style="color:blue;font-size: 15px">Video that will we shown on join us card of center</b>', max_length=500, null=True, verbose_name='Embeded Url'),
        ),
    ]
