# Generated by Django 3.2.3 on 2021-08-07 12:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0012_auto_20210806_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_center',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
