# Generated by Django 3.2.3 on 2021-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0013_alter_research_center_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='video',
            field=models.TextField(blank=True, help_text='<b style="color:green;font-size: 12px">*IMPORTANT* Only add either Video link or Image, If you add both, only the image will be shown</b>', null=True),
        ),
    ]
