# Generated by Django 3.2.3 on 2021-08-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0016_auto_20210808_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='short_description',
            field=models.TextField(blank=True, help_text='<b style="color:dodgerblue;font-size: 12px">Description of the card shown. *MAX_Length = 250 characters"</b>', max_length=250, null=True),
        ),
    ]
