# Generated by Django 3.2.3 on 2021-08-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0004_alter_career_talk_embeded_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_talk',
            name='embeded_video_link',
            field=models.TextField(blank=True, help_text='<b style="color:green;font-size: 12px">*IMPORTANT* Only add either Video link or Image, If you add both, only the image will be shown</b>', null=True),
        ),
    ]
