# Generated by Django 3.2.3 on 2021-08-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0005_alter_career_talk_embeded_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career_talk',
            name='is_active',
        ),
        migrations.AddField(
            model_name='career_talk',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
    ]
