# Generated by Django 3.2.3 on 2021-08-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, help_text='<b style="color:dodgerblue;font-size: 12px">Description of the card shown on all courses page. *MAX_Length = 250 characters"</b>', max_length=250, null=True),
        ),
    ]
