# Generated by Django 3.2.3 on 2021-08-07 15:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='contests.Category'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
