# Generated by Django 3.2.3 on 2021-08-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_contest_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='description',
            new_name='short_description',
        ),
    ]
